"""
config.py — Central Configuration for the Multi-Hazard AI/ML Pipeline
=======================================================================
Single source of truth for all constants, file paths, feature definitions,
model hyperparameters, and operational thresholds used across the pipeline.

All other modules import from here — do NOT hardcode values elsewhere.

Project: AI-Assisted Multi-Hazard Early Warning and Cascade Risk Assessment System
Region:  Sikkim, Himalayan India (prototype)
Phase:   Prototype / SIH 2026
"""

import os
from pathlib import Path

# ---------------------------------------------------------------------------
# PROTOTYPE WARNING  (display wherever output is surfaced to users)
# ---------------------------------------------------------------------------

PROTOTYPE_WARNING: str = (
    "This is a prototype system. Risk probabilities are estimates based on "
    "a simulated training dataset. Model has not been validated against real "
    "Himalayan landslide events. Do not use for operational emergency decisions."
)

# ---------------------------------------------------------------------------
# DIRECTORY LAYOUT
# ---------------------------------------------------------------------------
# Compute absolute paths relative to this file so the package is portable.
# Assumes the installed layout:
#   ml/
#     src/config.py   <- this file
#     data/
#     models/
#     reports/

SRC_DIR: Path = Path(__file__).resolve().parent          # ml/src/
ML_DIR: Path = SRC_DIR.parent                            # ml/
DATA_DIR: Path = ML_DIR / "data"                         # ml/data/
MODELS_DIR: Path = ML_DIR / "models"                     # ml/models/
REPORTS_DIR: Path = ML_DIR / "reports"                   # ml/reports/

# Ensure critical directories exist at import time (idempotent)
for _d in (DATA_DIR, MODELS_DIR, REPORTS_DIR):
    _d.mkdir(parents=True, exist_ok=True)

# ---------------------------------------------------------------------------
# DATA FILES
# ---------------------------------------------------------------------------

PROTOTYPE_CSV: Path = DATA_DIR / "prototype_training_data.csv"
"""Synthetic training CSV generated by data_loader.generate_synthetic_data()."""

# ---------------------------------------------------------------------------
# SYNTHETIC DATA GENERATION PARAMETERS
# ---------------------------------------------------------------------------

N_SAMPLES_TOTAL: int = 5_000
"""Total number of rows in the synthetic prototype dataset."""

N_POSITIVES: int = 400
"""Number of positive (landslide=1) samples in synthetic data (8% prevalence)."""

N_NEGATIVES: int = N_SAMPLES_TOTAL - N_POSITIVES   # 4600
"""Number of negative (landslide=0) samples."""

SYNTHETIC_RANDOM_STATE: int = 42
"""NumPy / sklearn random seed for reproducibility."""

MISSING_VALUE_FRACTION: float = 0.07
"""Fraction of values to randomly set to NaN in the synthetic dataset (7%)."""

# Northeast India bounding box (WGS-84) — covers all 8 states
LAT_MIN: float = 21.5   # Tripura southern tip
LAT_MAX: float = 30.0   # Arunachal Pradesh northern boundary
LON_MIN: float = 87.0   # Sikkim western edge
LON_MAX: float = 98.0   # Arunachal Pradesh eastern edge

# Synthetic timestamp range
TIMESTAMP_START: str = "2018-01-01"
TIMESTAMP_END: str = "2023-12-31"

# ---------------------------------------------------------------------------
# FEATURE DEFINITIONS
# ---------------------------------------------------------------------------

#: All 20 raw feature column names expected in the training CSV and at
#: inference time.  The order here is canonical -- preprocessing and feature
#: engineering must preserve this order before model input.
RAWFEATURE_NAMES: list = [
    "rainfall_30min_mm",             # NASA GPM IMERG: 30-minute accumulation
    "rainfall_3hr_mm",               # NASA GPM IMERG: 3-hour accumulation
    "rainfall_24hr_mm",              # NASA GPM IMERG: 24-hour accumulation
    "rainfall_3day_mm",              # NASA GPM IMERG: 3-day accumulation
    "rainfall_7day_mm",              # NASA GPM IMERG: 7-day accumulation
    "rainfall_intensity",            # Derived: rainfall_30min_mm / 0.5 (mm/hr)
    "antecedent_rainfall_anomaly",   # Derived: 7-day total - climatological mean
    "soil_moisture_pct",             # IoT / proxy: % volumetric water content
    "soil_moisture_change_rate",     # Derived: delta_soil_moisture / delta_time
    "elevation_m",                   # SRTM 30m DEM: metres above sea level
    "slope_deg",                     # DEM-derived: slope in degrees (0-90)
    "aspect_deg",                    # DEM-derived: aspect in degrees (0-360)
    "ndvi",                          # Sentinel-2 L2A: (B8-B4)/(B8+B4)
    "land_cover_class",              # Sentinel-2 classified: categorical
    "historical_landslide_density",  # ISRO Landslide Atlas: count within 5 km
    "distance_to_river_km",          # GIS/OSM: nearest river distance
    "distance_to_road_km",           # GIS/OSM / Bhuvan: nearest road distance
    "tilt_change_deg",               # IoT inclinometer / proxy: tilt delta
    "temperature_C",                 # IMD AWS / proxy: surface air temperature
    "data_freshness_score",          # Derived: FRESH/RECENT/STALE/MISSING -> float
]

#: Subset of RAWFEATURE_NAMES that are purely numerical (used for imputation,
#: scaling, and missing-value injection).
NUMERICAL_FEATURES: list = [
    f for f in RAWFEATURE_NAMES if f != "land_cover_class"
]

#: Categorical features list (currently only land_cover_class).
CATEGORICAL_FEATURES: list = ["land_cover_class"]

#: Meta-columns that are NOT model input features (kept in DataFrame for
#: reference, splitting, and debugging but excluded from X matrices).
META_COLUMNS: list = [
    "latitude",
    "longitude",
    "timestamp",
    "landslide_occurred",   # target -- excluded from features
]

#: Target column name.
TARGET_COLUMN: str = "landslide_occurred"

#: Valid categories for land_cover_class.
LAND_COVER_CLASSES: list = ["forest", "bare", "agricultural", "built"]

# ---------------------------------------------------------------------------
# FEATURE ENGINEERING PARAMETERS
# ---------------------------------------------------------------------------

#: Climatological 7-day mean rainfall (mm) for Sikkim during monsoon season.
#: PROTOTYPE ASSUMPTION: Derived from published IMD normals for Gangtok (~80 mm/week
#: during June-September).  Replace with pixel-wise climatological rasters from
#: GPM IMERG monthly climatology before production use.
CLIMATOLOGICAL_7DAY_MEAN_MM: float = 80.0

#: Tilt change threshold (degrees) above which tilt_movement_detected = 1.
TILT_MOVEMENT_THRESHOLD_DEG: float = 0.5

#: Data freshness mapping from age-of-observation category to score (0-1).
DATA_FRESHNESS_SCORES: dict = {
    "FRESH":   1.0,   # < 1 hour old
    "RECENT":  0.7,   # 1-6 hours old
    "STALE":   0.4,   # 6-24 hours old
    "MISSING": 0.0,   # Data absent / unretrievable
}

# ---------------------------------------------------------------------------
# VALIDATION / PLAUSIBILITY RANGES
# ---------------------------------------------------------------------------

#: (min, max) plausible bounds per feature.  Values outside these ranges are
#: treated as erroneous and replaced with NaN before imputation.
FEATURE_VALID_RANGES: dict = {
    "rainfall_30min_mm":            (0.0,  500.0),
    "rainfall_3hr_mm":              (0.0,  500.0),
    "rainfall_24hr_mm":             (0.0,  500.0),
    "rainfall_3day_mm":             (0.0,  500.0),
    "rainfall_7day_mm":             (0.0,  500.0),
    "rainfall_intensity":           (0.0, 1000.0),
    "antecedent_rainfall_anomaly":  (-200.0, 400.0),
    "soil_moisture_pct":            (0.0,  100.0),
    "soil_moisture_change_rate":    (-50.0,  50.0),
    "elevation_m":                  (0.0, 9000.0),
    "slope_deg":                    (0.0,   90.0),
    "aspect_deg":                   (0.0,  360.0),
    "ndvi":                         (-1.0,    1.0),
    "historical_landslide_density": (0.0,  200.0),
    "distance_to_river_km":         (0.0,  100.0),
    "distance_to_road_km":          (0.0,  100.0),
    "tilt_change_deg":              (-10.0,  10.0),
    "temperature_C":                (-20.0,  55.0),
    "data_freshness_score":         (0.0,    1.0),
}

# ---------------------------------------------------------------------------
# MODEL PERSISTENCE PATHS
# ---------------------------------------------------------------------------

MODEL_PATHS: dict = {
    "logistic_regression": MODELS_DIR / "logistic_regression.joblib",
    "random_forest":       MODELS_DIR / "random_forest.joblib",
    "xgboost":             MODELS_DIR / "xgboost.joblib",
    "best_model":          MODELS_DIR / "best_model.joblib",
    "preprocessor":        MODELS_DIR / "preprocessor.joblib",
    "model_metadata":      MODELS_DIR / "model_metadata.json",
}

# ---------------------------------------------------------------------------
# RISK LEVEL THRESHOLDS  (probability -> risk category)
# ---------------------------------------------------------------------------
# Thresholds are provisional prototype values.  They must be validated
# against real operational data before production use.

RISK_THRESHOLDS: dict = {
    "LOW":       (0.00, 0.35),
    "MODERATE":  (0.35, 0.55),
    "HIGH":      (0.55, 0.75),
    "VERY_HIGH": (0.75, 1.01),
}
"""Probability intervals (inclusive lower, exclusive upper) mapped to risk category."""

RISK_COLORS: dict = {
    "LOW":       "green",
    "MODERATE":  "yellow",
    "HIGH":      "orange",
    "VERY_HIGH": "red",
}

# ---------------------------------------------------------------------------
# TRAINING HYPERPARAMETERS
# ---------------------------------------------------------------------------

# Random Forest
RF_PARAMS: dict = {
    "n_estimators":     200,
    "max_depth":        None,
    "min_samples_leaf": 5,
    "class_weight":     "balanced",
    "oob_score":        True,
    "n_jobs":           -1,
    "random_state":     SYNTHETIC_RANDOM_STATE,
}

# XGBoost  (scale_pos_weight set dynamically in train.py)
XGB_PARAMS: dict = {
    "n_estimators":     300,
    "max_depth":        6,
    "learning_rate":    0.05,
    "subsample":        0.8,
    "colsample_bytree": 0.8,
    "use_label_encoder": False,
    "eval_metric":      "aucpr",
    "random_state":     SYNTHETIC_RANDOM_STATE,
    "tree_method":      "hist",
}

# Logistic Regression
LR_PARAMS: dict = {
    "class_weight": "balanced",
    "max_iter":     1000,
    "random_state": SYNTHETIC_RANDOM_STATE,
}

# Cross-validation
CV_N_SPLITS: int = 5

# Temporal train/test split ratio (train on earliest fraction)
TEMPORAL_TRAIN_RATIO: float = 0.80

# ---------------------------------------------------------------------------
# REPORTING
# ---------------------------------------------------------------------------

EVALUATION_REPORT_PATH: Path = REPORTS_DIR / "evaluation_report.txt"
SHAP_SUMMARY_PNG: Path = REPORTS_DIR / "shap_summary.png"
SHAP_FORCE_HTML: Path = REPORTS_DIR / "shap_force_example.html"

# ---------------------------------------------------------------------------
# LOGGING FORMAT
# ---------------------------------------------------------------------------

LOG_FORMAT: str = "%(asctime)s | %(levelname)-8s | %(name)s | %(message)s"
LOG_DATE_FORMAT: str = "%Y-%m-%d %H:%M:%S"

# ---------------------------------------------------------------------------
# DATA LOADER CHUNK SIZE
# ---------------------------------------------------------------------------

CSV_CHUNK_SIZE: int = 10_000
"""Number of rows per chunk when reading large CSVs with pd.read_csv(chunksize=...)."""

# ---------------------------------------------------------------------------
# COMPATIBILITY ALIASES
# ---------------------------------------------------------------------------
ROOT_DIR: Path = ML_DIR
TRAINING_DATA_PATH: Path = PROTOTYPE_CSV
BEST_MODEL_PATH: Path = MODEL_PATHS["best_model"]
PREPROCESSOR_PATH: Path = MODEL_PATHS["preprocessor"]
MODEL_METADATA_PATH: Path = MODEL_PATHS["model_metadata"]
SHAP_SUMMARY_PATH: Path = SHAP_SUMMARY_PNG
SHAP_FORCE_PATH: Path = SHAP_FORCE_HTML
FEATURE_RANGES: dict = FEATURE_VALID_RANGES
CHUNKSIZE: int = CSV_CHUNK_SIZE
CV_FOLDS: int = CV_N_SPLITS
RANDOM_STATE: int = SYNTHETIC_RANDOM_STATE
TRAIN_TEST_SPLIT_RATIO: float = TEMPORAL_TRAIN_RATIO

FRESHNESS_THRESHOLDS: dict = {
    "FRESH":   (0.0,  6.0,  1.0),   # < 6 hours old -> score 1.0
    "RECENT":  (6.0,  24.0, 0.7),   # 6-24 hours -> score 0.7
    "STALE":   (24.0, 72.0, 0.4),   # 1-3 days -> score 0.4
    "MISSING": (72.0, float("inf"), 0.0),  # > 3 days -> score 0.0
}

